%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/nico/Desktop/220519_Area+Circumference+Angles_DP.xlsx
%    Worksheet: Area+Circumference
%
% Auto-generated by MATLAB on 22-Jul-2022 12:30:31

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = "Area+Circumference";
opts.DataRange = "A2:F21";

% Specify column names and types
opts.VariableNames = ["Day", "Sample_ID", "Areaum2", "Circumferenceum", "Lengthum", "LC"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Import the data
AreaCircumferenceAnglesDP = readtable("/Users/jones/Downloads/Arispe Collab/Observed Data/220519_Area+Circumference+Angles_DP.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% plot data
figure
sorted=sortrows([AreaCircumferenceAnglesDP{:,'Day'} AreaCircumferenceAnglesDP{:,'Lengthum'}]);
sorted_day = sorted(:,1);
sorted_length = sorted(:,2);
sorted=sortrows([AreaCircumferenceAnglesDP{:,'Day'} AreaCircumferenceAnglesDP{:,'Circumferenceum'}]);
sorted_circ = sorted(:,2);
%f=fit(AreaCircumferenceAnglesDP{:,'Day'},AreaCircumferenceAnglesDP{:,'Lengthum'},'poly2');
%xx=linspace(0,60,1000);
%yy = spline(sorted_day,sorted_length,xx);
%plot(xx,yy)

figure(3)
    subplot(3,1,1) 
     scatter(sorted_day, sorted_length,'MarkerEdgeColor',[0 0.4470 0.7410],'LineWidth',1);
     legend('Length (um)') 
     grid
       xlabel('Time (days)')
       ylabel('Length (um)')
      hold on

    subplot(3,1,2) 
     scatter(sorted_day, sorted_circ,'MarkerEdgeColor',[0.8500 0.3250 0.0980],'LineWidth',1);
      legend('Circumference (um)')
       grid
       xlabel('Time (days)')
       ylabel('Circumference (um)')
       hold on
    subplot(3,1,3) 
     scatter(x,AreaCircumferenceAnglesDP{:,'Lengthum'}./AreaCircumferenceAnglesDP{:,'Circumferenceum'},'MarkerEdgeColor',[0.4940 0.1840 0.5560], 'LineWidth',1);
      legend('Length / Circumference')
       grid
       xlabel('Time (days)')
       ylabel('Length / Circumference')
       hold on
     hold off